name: Build and save apk
on:
  push:
    branches:
      - master
jobs:
  prepare_tools:
    name: Prepare tools to generate the APK
    runs-on: ubuntu-latest
    steps:
      - name: Get code from the current repository
        uses: actions/checkout@v2
        
      - name: Install Java
        uses: actions/setup-java@v1
        with:
            java-version: 17
            
      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.19
          
      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install --legacy-peer-deps
        
      - name: Convert Windows line endings to Linux from the gradlew file
        run: sudo apt update && sudo apt install dos2unix && cd android && dos2unix ./gradlew && cd ..
      
      - name: Make ./gradlew command executable
        run: cd android && chmod +x ./gradlew && cd ..

      - name: Build Ionic assets
        run: ionic capacitor build android --prod

      - name: Copy generated assets from Ionic to Capacitor Android platform
        run: npx cap copy android && npx cap update android

      - name: Generate APK
        run: cd android && ./gradlew assembleDebug && cd ..

      - name: Upload generated APK to Github
        uses: actions/upload-artifact@v3
        with:
            name: app-build
            path: ./android/app/build/outputs/apk/debug/app-debug.apk
            retention-days: 3

  save_apk_on_hosting:
    name: Copy APK
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./dist/build
      - name: 📂 Upload files with ftp
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/build/
          server-dir: ./projects/shiptracker/shiptracker.android/



  # - name: Upload generated APK to Github
  #   uses: actions/upload-artifact@v3
  #   with:
  #       name: app-build
  #       path: ./android/app/build/outputs/apk/debug/app-debug.apk
  #       retention-days: 3

  # save_apk_on_hosting:
  #   name: Prepare tools to generate the APK
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download app artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: app-build
  #     - name: 📂 Upload files with ftp
  #       uses: SamKirkland/FTP-Deploy-Action@4.0.0
  #       with:
  #         server: ${{ secrets.ftp_host }}
  #         username: ${{ secrets.ftp_username }}
  #         password: ${{ secrets.ftp_password }}
  #         server-dir: ./projects/shiptracker/shiptracker.android/


  # build:
  #   name: Greeting
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Run a multi-line script
  #     run: |
  #       echo Add other actions to build,
  #       echo test, and deploy your project.
